#! /bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="1.0.0"

#. $PROGPATH/utils.sh


print_usage() {
	echo "Usage: $PROGNAME [ disk name ] [ state mode ]"
}

print_revision() {
	echo "$PROGNAME"
	echo "Nagios plugin to monitor the disk state"
	echo "Version: $REVISION"
	echo "Johann Baudy - http://www.gnu.org/licenses/gpl-2.0.txt"
}

print_help() {	
	echo ""
	print_usage
	echo ""
	echo "This plugin checks disk space availability."
	echo ""
	print_revision
	echo ""
	support
	exit 0
}

case "$1" in
	--help)
		print_help
		exit 0
		;;
	-h)
		print_help
		exit 0
		;;
	--version)
   		print_revision
		exit 0
		;;
	-v)
		print_revision
		exit 0
		;;
	*)
		if [ -n "$2" ] ; then
			MODE=$2
		else
			MODE="standby"
		fi	
		
		if [ -n "$1" ] ; then
			sudo /sbin/hdparm -C $1
			STATE=$(sudo /sbin/hdparm -C $1 | awk 'FNR == 3 {print $4}')
			#echo $INFO
			if [ "$STATE" == "$MODE" ] ; then
				echo "MODE OK"
				exit 0			
			else	
				echo "DISK CRITICAL"
				exit 1
			fi
		else
			echo "DISK UNKNOWN - Argument not specified"
			exit -1
		fi	
		;;
esac
