#! /bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="1.0.0"

#. $PROGPATH/utils.sh


print_usage() {
	echo "Usage: $PROGNAME [ Temperature sensor name's. eg. 'CPU temp' ]"
}

print_revision() {
	echo "$PROGNAME"
	echo "Nagios plugin to monitor the disk space"
	echo "Version: $REVISION"
	echo "Johann Baudy - http://www.gnu.org/licenses/gpl-2.0.txt"
}

print_help() {	
	echo ""
	print_usage
	echo ""
	echo "This plugin checks disk space availability."
	echo ""
	print_revision
	echo ""
	support
	exit 0
}

case "$1" in
	--help)
		print_help
		exit 0
		;;
	-h)
		print_help
		exit 0
		;;
	--version)
   		print_revision
		exit 0
		;;
	-v)
		print_revision
		exit 0
		;;
	*)
		if [ -n "$2" ] ; then
			LIMIT=$2
		else
			LIMIT=1
		fi	
		
		if [ -n "$1" ] ; then
			df -H | grep -vE '^Filesystem|tmpfs|cdrom|cgmanager|udev'
			AVAIL=$(df --block-size=1G| grep $1 | awk '{print $4}')
			#echo $INFO
			if [ "$AVAIL" -gt $LIMIT ] ; then
				echo "DISK OK"
				exit 0			
			else	
				if [ "$AVAIL" -gt 0] ; then
					echo "DISK WARNING"
					exit 2
				else
					echo "DISK CRITICAL"
					exit 1
				fi
			fi
		else
			echo "DISK UNKNOWN - Argument not specified"
			exit -1
		fi	
		;;
esac
